const AppActionsConstants = {
    UPDATE_IS_SIGN_IN_OPEN: 'UPDATE_IS_SIGN_IN_OPEN',
    UPDATE_IS_REGISTER_OPEN: 'UPDATE_IS_REGISTER_OPEN',
    VERIFY_TOKEN: 'VERIFY_TOKEN',
    VERIFY_TOKEN_FAILURE: 'VERIFY_TOKEN_FAILURE',
    CLOSE_LOADING: 'CLOSE_LOADING',
    OPEN_LOADING: 'OPEN_LOADING',
};

export { AppActionsConstants}
