const LoginActionsConstants = {
    IS_USERNAME_EXIST: 'IS_USERNAME_EXIST',
    IS_USER_EXIST_SUCCESS: 'IS_USER_EXIST_SUCCESS',
    LOADֹֹֹ_USERNAMES_FAILURE: 'LOADֹֹֹ_USERNAMES_FAILURE',
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FB: 'SIGN_IN_FB',
    SIGN_IN_FB_SUCCESS: 'SIGN_IN_FB_SUCCESS',
    SET_LAN_LNG:'SET_LAN_LNG',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
};

export {LoginActionsConstants}
