const MainActionsConstants = {
    LOADֹֹֹ_USER_PROFILES: 'LOADֹֹֹ_USER_PROFILES',
    LOADֹֹֹ_USER_PROFILES_SUCCESS: 'LOADֹֹֹ_USER_PROFILES_SUCCESS',
    LOADֹֹֹ_USER_PROFILES_FAILURE: 'LOADֹֹֹ_USER_PROFILES_FAILURE',
    EDIT_USER_PROFILE: 'EDIT_USER_PROFILE',
    CLEAR_AVATAR_PREVIEW: 'CLEAR_AVATAR_PREVIEW',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    SUBMIT_REVIEW: 'SUBMIT_REVIEW',
    LOADֹֹֹ_USER_REVIEWS: 'LOADֹֹֹ_USER_REVIEWS',
    LOADֹֹֹ_USER_REVIEWS_SUCCESS: 'LOADֹֹֹ_USER_REVIEWS_SUCCESS',
    LOADֹֹֹ_RESTAURANT_REVIEWS: 'LOADֹֹֹ_RESTAURANT_REVIEWS',
    LOADֹֹֹ_RESTAURANT_REVIEWS_SUCCESS: 'LOADֹֹֹ_RESTAURANT_REVIEWS_SUCCESS',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DATA_EDIT_REVIEW: 'DATA_EDIT_REVIEW',
    EDIT_REVIEW: 'EDIT_REVIEW',
    SET_REVIEWS_BY_USER_NAME: 'SET_REVIEWS_BY_USER_NAME', //TODO CHANGE TO SEARCH
    SEARCH_REVIEWS_BY_RESTAURANT_NAME: 'SEARCH_REVIEWS_BY_RESTAURANT_NAME',

};

export {MainActionsConstants}
